### ISSUE TITLE
customization issue

### ISSUE THREAD

**Issue by drissDean** [cptanalatriste/isula#7]
Hello.

I've replaced the tsp file with data coming from a database and it works well. Now I want to replace the classic Euclidean distance metrics with estimated travel time between points.
I've already written the methods for that and then, given two points, I can tell how many seconds it'll take to travel from one of them to the other.
I don't know how to integrate that in the system.

Your help would be very appreciated.

**Comment by cptanalatriste** [comment]
Hello @drissDean !

Isula's implementation of ACO algorithms look for solutions with the **minimum cost**. These solutions are generated by instances of `Ant`, and the cost is obtained by the  method `Ant::getSolutionCost()`. In a TSP instance, the cost is expressed in terms of distance. If you have a different cost metric, just override `Ant::getSolutionCost()` with the logic that suits your domain.

**Comment by cptanalatriste** [comment]
Hi @drissDean ,

I would approach it this way:

1. Extend `AntForTsp `, for example `CustomAntForTsp`, overriding  `getSolutionCost()`. According to your problem, you might also need to override `getHeuristicValue()`.
2. Use these new type `CustomAntForTsp` when creating the `AntColony` instance for your `AcoProblemSolver`. Take a look at the `getAntColony` method at [AcoTspWithIsula](https://github.com/cptanalatriste/aco-tsp/blob/master/src/main/java/tsp/isula/sample/AcoTspWithIsula.java).

Good luck!

**Comment by drissDean** [comment]
Alright, sir. Thank you so much.
